### ISSUE TITLE
[server] Unique enity io fixup breaks some maps loading

### ISSUE THREAD

**Issue by tsarevichdm** [dimhotepus/SourceEngine2007#16]
When going up in lift to dr. Breen, entity io fixup application miss `g_iCurrentTemplateInstance` unique values (> 100).
Also,  entity io fixup application mess map data, which leads to load failure.

**Comment by dimhotepus** [comment]
Fixed in:
https://github.com/dimhotepus/SourceEngine2007/commit/c1c414ac7b5187a14b82eb3d77a6ad18fe7df6a0
